package com.footballmanager.domain.model.valueobject;

public class SeasonId {
    private final int value;

    private SeasonId(int value) {
        this.value = value;
    }

    public static SeasonId of(int value) { return new SeasonId(value); }
    public static SeasonId generate() { throw new UnsupportedOperationException("SeasonId is generated by DB (SERIAL)"); }
    public int getValue() { return value; }
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SeasonId seasonId = (SeasonId) o;
        return value == seasonId.value;
    }
    @Override
    public int hashCode() { return Integer.hashCode(value); }
    @Override
    public String toString() { return Integer.toString(value); }
}
